# Generated by Django 5.1.5 on 2025-01-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='Summary', max_length=200),
        ),
    ]
