# Generated by Django 5.1.5 on 2025-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(choices=[('Personal blogs', 'Personal blogs'), ('Food', 'Food'), ('Education', 'Education'), ('History', 'History'), ('Corporate blogs', 'Corporate blogs'), ('Listicles', 'Listicles'), ('nfographics', 'nfographics'), ('Reviews', 'Reviews'), (' How-to guides', ' How-to guides'), ('Comparisons', 'Comparisons'), ('Vlogs', 'Vlogs'), ('Memes', 'Memes'), ('Affiliate blogs', 'Affiliate blogs'), ('Niche blogs', 'Niche blogs'), (' DIY blogs', ' DIY blogs')], default='Personal blogs', max_length=200),
        ),
    ]
