# Generated by Django 5.1.5 on 2025-01-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_tag_remove_blog_tags_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Personal blogs', 'Personal blogs'), ('Food', 'Food'), ('Education', 'Education'), ('History', 'History'), ('Corporate blogs', 'Corporate blogs'), ('Listicles', 'Listicles'), ('Infographics', 'Infographics'), ('Reviews', 'Reviews'), ('How-to guides', 'How-to guides'), ('Comparisons', 'Comparisons'), ('Vlogs', 'Vlogs'), ('Memes', 'Memes'), ('Affiliate blogs', 'Affiliate blogs'), ('Niche blogs', 'Niche blogs'), ('DIY blogs', 'DIY blogs')], max_length=50, unique=True),
        ),
    ]
