# Generated by Django 5.1.5 on 2025-01-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(choices=[('Personal blogs', 'Personal blogs'), ('Food', 'Food'), ('Education', 'Education'), ('History', 'History'), ('Corporate blogs', 'Corporate blogs'), ('Listicles', 'Listicles'), ('Infographics', 'Infographics'), ('Reviews', 'Reviews'), ('How-to guides', 'How-to guides'), ('Comparisons', 'Comparisons'), ('Vlogs', 'Vlogs'), ('Memes', 'Memes'), ('Affiliate blogs', 'Affiliate blogs'), ('Niche blogs', 'Niche blogs'), ('DIY blogs', 'DIY blogs')], default='Personal blogs', max_length=100),
        ),
    ]
